### ISSUE TITLE
Error in  linAlg0111.pg, and fix.

### ISSUE THREAD

**Issue by TimAlderson** [ULeth-Math-CS/uleth-math-webwork-library#3]
Error in: 

ULethQuestionBank/MATH1410-ElementaryLinearAlgebra/010-SystemsOfLinearEquations/linAlg0111.pg

Issue with part 8 accepting the same answer as part 7 (with rank 3 matrix).   

Fix: Added condition “D not equal to C” (line 76), and added line 219 (as attached).

Tim.
[linAlg0111a.pg.tex.zip](https://github.com/ULeth-Math-CS/uleth-math-webwork-library/files/3601402/linAlg0111a.pg.tex.zip)

**Comment by sean-fitzpatrick** [comment]
Thanks for the report! I've added your changes and pushed the new version on the master branch.

PS: the attachment is fine, but if you're so inclined, you can streamline the process by forking the repository and sending a pull request.

**Comment by sean-fitzpatrick** [comment]
Fixed in commit abe9348

**Comment by TimAlderson** [comment]
Thanks Sean.

I read up on that process, and hopefully go that way next time.

All the best,

Tim.
